<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My TimesheetTimesheet PeriodMarch2026SMTWTFS</name>
   <tag></tag>
   <elementGuidId>453be1c9-8df8-4bd3-8bc8-f85be1338410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-background-container ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e11ada7-1d42-4d79-aa4d-97ace62e6e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>d736c63a-cded-44af-9395-e839fdf4386b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My TimesheetTimesheet PeriodMarch2026SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseNo Timesheets FoundStatus:  Create Timesheet </value>
      <webElementGuid>51055d9e-e74a-4ae0-8cb6-0f0db0a2cf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-961d3054e547dfd0ca62599ffc743901</value>
      <webElementGuid>26757ef9-c9a1-4045-8a03-722551bd8b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-background-container ')]</value>
      <webElementGuid>5128e614-59f9-4704-89fb-3df80d709fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-background-container ')]</value>
      <webElementGuid>33462dac-2825-450b-b541-e2b102db201d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My TimesheetTimesheet PeriodMarch2026SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseNo Timesheets FoundStatus:  Create Timesheet ' or . = 'My TimesheetTimesheet PeriodMarch2026SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseNo Timesheets FoundStatus:  Create Timesheet ')]</value>
      <webElementGuid>817d76c4-4b24-4697-87ae-7bdc14f924c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
