<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_March</name>
   <tag></tag>
   <elementGuidId>eb573018-b5f1-4a08-99fa-2e37227366ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-calendar-dropdown--option ') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.oxd-calendar-dropdown--option:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c3c0150a-a8e7-4847-98d2-3d4fabf96d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-calendar-dropdown--option --selected</value>
      <webElementGuid>611097a2-9dcb-4e0c-be89-cc74713a3ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>March</value>
      <webElementGuid>ad3b35ca-0f7e-43b4-84eb-e075f3e2dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5fab6459b97a1751e4b5ec237df364a2</value>
      <webElementGuid>5096df5a-133f-4dc0-9b71-0e65561b9797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-calendar-dropdown--option ') and (position() = 3)]</value>
      <webElementGuid>8f86d2f4-89ce-490c-81e1-17ed089d0a39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-calendar-dropdown--option ') and (position() = 3)]</value>
      <webElementGuid>08496592-8eb5-47e7-bb40-e1f17c9a3819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'March' or . = 'March')]</value>
      <webElementGuid>6e544fb5-8b13-4327-af24-6680d7da76b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
