<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_Project- Select</name>
   <tag></tag>
   <elementGuidId>e58a4c72-d0b2-46a2-82c6-35a3e8ecd5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-timesheet-table-body-row ') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-timesheet-table-body-row:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>2aa42727-6f85-4d5d-9b77-fd435139c88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-timesheet-table-body-row</value>
      <webElementGuid>dbf78332-d684-4975-a32c-ef0c186aecdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project-- Select --</value>
      <webElementGuid>6d6d588f-9447-4da4-bb8c-8b89a5ba3708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18a99a390cc98bdd0c01959564788839</value>
      <webElementGuid>369690a2-7c6c-46aa-8666-41fefd97caf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-timesheet-table-body-row ') and (position() = 2)]</value>
      <webElementGuid>a4e29c9c-4799-482d-8cae-0ac0c92f4561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-timesheet-table-body-row ') and (position() = 2)]</value>
      <webElementGuid>18c0a63c-7bd7-4a19-90a5-e793d8e9cc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[(text() = 'Project-- Select --' or . = 'Project-- Select --')]</value>
      <webElementGuid>28872a96-de34-42d6-9446-6c0f9aa13cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
