<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Olivia Hayes0405</name>
   <tag></tag>
   <elementGuidId>a0a4c980-e4dd-459c-9653-dcec18115535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-leave-card ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-leave-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3eff7e5-d4cf-43b9-b7a0-681becae15de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-leave-card</value>
      <webElementGuid>2a5244ab-b74b-4a6f-8d54-d37051eab29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Olivia Hayes0405</value>
      <webElementGuid>c4ed01b6-e317-47ce-af0b-9e5a896efafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5e806e4fc07582746e4a79446efe8e14</value>
      <webElementGuid>ee0b6d65-8a60-4bce-b7a7-aa9f4e3cf7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-leave-card ')]</value>
      <webElementGuid>d433f4f8-d94e-4a2c-a440-7e6ee194987f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-leave-card ')]</value>
      <webElementGuid>1956a58f-8974-4fe1-91cc-11d1fdd2c55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Olivia Hayes0405' or . = 'Olivia Hayes0405')]</value>
      <webElementGuid>75e45833-721a-4134-a530-4d76c471bc45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
